version: '3.8'
services:
  db:
    image: postgres:15
    container_name: stardew_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stardew_planner
    ports:
      - "5432:5432"